collections:
   pages:
     output: true
     permalink: /:path/
   notes:
     output: true
     permalink: /notes/:path/
     
# --- Required options --- #

# Name of website
title: Vinit Joglekar

# Your name to show in the footer
author: Vinit Joglekar

# --- Logo --- #
# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

# --- Colours / background image --- #
# Personalize the colours in your website. Colour values can be any valid CSS colour
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: "the id"

# Google Tag Manager ID
#gtm: ""

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#      comments: true  # add comments to all blog posts
#      social-share: true # add social media sharing buttons to all blog posts
#  -
#    scope:
#      path: "" # any file that's not a post will be a "page" layout by default
#    values:
#      layout: "post"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
#  - README.md
  - screenshot.png
  - docs/

#plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
